name: Publish GitPublish Website

on:
  push:
    branches: [main]

permissions:
  id-token: write
  pages: write
  contents: read

jobs:
  deploy:
    environment:
      name: github-pages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up site directory
        run: |
          mkdir -p site
          # Copy everything except .github to site/
          find . -mindepth 1 -maxdepth 1 ! -name '.github' -exec cp -r {} site/ \;
          # Overwrite index.html with homepage
          cp admin/homepage.html site/index.html
      
      - name: List site directory contents
        run: ls -lR site

      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
