name: Publish GitPublish Website

on:
  push:
    branches: [main]

permissions:
  id-token: write
  pages: write
  contents: read

jobs:
  deploy:
    environment:
      name: github-pages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up homepage
        run: |
          mkdir -p site
          cp admin/homepage.html site/index.html

      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
